# Generated by Django 3.1 on 2020-08-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('audio', models.FileField(blank=True, upload_to='audio/')),
            ],
        ),
    ]
